name: Build and deploy ASP.Net Core app to Azure Web App - product-management-system

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Add dotnet tools to PATH
        run: echo "${{ runner.tool_cache }}/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore ./EventManagementSystem/EventManagementSystem.sln

      - name: Build with dotnet
        run: dotnet build ./EventManagementSystem/EventManagementSystem.sln --configuration Release

      - name: Apply migrations
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        run: dotnet ef database update --startup-project ./EventManagementSystem/EventManagementSystem.csproj --project ./EventManagementSystem.DAL/EventManagementSystem.DAL.csproj

      - name: dotnet publish
        run: dotnet publish ./EventManagementSystem/EventManagementSystem.sln -c Release -o "${{runner.temp}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{runner.temp}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7A2E4E3288324C36B20E52CB637045C1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4BA09044CE7945398A5D5692C04F4461 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EF1A7E5B37C44A00819D96AC49838057 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'product-management-system'
          slot-name: 'Production'
          package: .
